title: <p align="center">Vivek Rajeev</p>
logo: /assets/img/logo.png
description: <p>
<b>Im just a dev who likes to have fun</b>
</p>
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
